### ISSUE TITLE
gnatmake/gprbuild in courses/fundamentals_of_ada/910_gpr_basics.rst

### ISSUE THREAD

**Issue by CyrilleComar** [AdaCore/training_material#1]
it doesn't make sense to show examples with gnatmake when the official project-awware builder is gprbuild. gnatmake official purpose is to build simple programs that do not require a project files. The current implementation of -P in gnatmake is that a call to gprbuild is made. At some point, this functionality will be made obsolescent so it seems better for the course to only speak about gprbuild when it comes to using projects
(nice work on the overall  courses btw)

**Comment by leogermond** [comment]
Hi Cyril, 

Thanks for reporting and sorry for the delayed response. The labs are being reworked and this is on the list of things we'll improve.

Best
